apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-node
spec:
  selector:
    matchLabels:
      app: hello-node
  replicas: 1 # deployment runs 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node
        image: sibendudas/hello-node
        #imagePullPolicy: Always
        #command: ["npm","start"]
        #command: ["/bin/bash", "-ce", "tail -f /dev/null" ]
        ports:
        - name: hello-node
          containerPort: 5000 #Endpoint is at port 5000 in the container
          protocol: TCP

