apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-node-deployment
spec:
  selector:
    matchLabels:
      app: hello-node
  replicas: 1 # deployment runs 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node
        image: sibendudas/hello-node:latest
        ports:
        - containerPort: 5000 #Endpoint is at port 5000 in the container
---
apiVersion: v1
kind: Service
metadata:
  name: hello-node-service
spec:
  type: NodePort #Exposes the service as a node port
  ports:
  - port: 30000
    targetPort: 5000
  selector:
    app: hello-node
